# Generated by Django 5.1.1 on 2024-09-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['done', '-created']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='date_time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='deadline_date_time',
            new_name='deadline',
        ),
    ]
